# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
cocoapods

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :build do

    gym(
	skip_codesigning: true, 
        skip_archive: true
    )
    hola
  end

  lane :hola do
    run_tests()
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :pepito do
    print("hola com estas?")
    # add actions here: https://docs.fastlane.tools/actions
  end
end

